definitions:
  request.CompanyAduitMaterialsReleaseReq:
    properties:
      company_id:
        type: integer
      company_type:
        type: integer
      corporation_info:
        $ref: '#/definitions/request.CorporationInfoStruct'
      main_body_info:
        $ref: '#/definitions/request.MainBodyStruct'
      operator_info:
        $ref: '#/definitions/request.OperatorInfoStruct'
    type: object
  request.CompanyMajorInfoImage:
    properties:
      business_license_img:
        type: string
      corporation_img:
        type: string
    type: object
  request.CorporationInfoStruct:
    properties:
      address:
        type: string
      corporation_img:
        $ref: '#/definitions/request.UserIdCardImage'
      due_date:
        type: string
      id_card_type:
        type: string
    type: object
  request.GetAuditStatusReq:
    properties:
      company_id:
        type: integer
      update_type:
        example: 1
        type: integer
      user_id:
        example: 87
        type: integer
    type: object
  request.GetAuditStatusRes:
    properties:
      status:
        example: 0
        type: integer
    type: object
  request.MainBodyStruct:
    properties:
      company_name:
        type: string
      credit_code:
        type: string
      due_date:
        type: string
      main_image:
        $ref: '#/definitions/request.CompanyMajorInfoImage'
    type: object
  request.OperatorInfoStruct:
    properties:
      id_card:
        type: string
      id_card_type:
        type: string
      name:
        type: string
      operator_img:
        $ref: '#/definitions/request.UserIdCardImage'
    type: object
  request.ReleaseGoodReq:
    properties:
      description:
        type: string
      images:
        items:
          type: string
        type: array
      titile:
        type: string
    type: object
  request.UpdateAuditStatusReq:
    properties:
      company_id:
        type: integer
      status:
        type: integer
      update_type:
        type: integer
      user_id:
        type: integer
    type: object
  request.UserAduitMaterialsReleaseReq:
    properties:
      address:
        type: string
      due_date:
        type: string
      id_card:
        type: string
      id_card_type:
        type: string
      images:
        $ref: '#/definitions/request.UserIdCardImage'
      name:
        type: string
      userID:
        type: integer
    type: object
  request.UserIdCardImage:
    properties:
      face_side_img:
        type: string
      national_side_img:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample Server pets
  title: Swagger Example API
  version: 0.0.1
paths:
  /certificate/UpdateUserAuditStatus:
    post:
      consumes:
      - application/json
      parameters:
      - description: user_id 用户id(update_type为1时必填), company_id 商户id(update_type为2时必填),
          update_type 更新类型(1.更新用户 2.更新商户), status 审核状态 0未审核 1审核中 2已审核
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateAuditStatusReq'
      produces:
      - application/json
      responses:
        "200":
          description: 审核状态更新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 更新审核状态
      tags:
      - UpdateUserAuditStatus
  /certificate/company_audit_material_release:
    post:
      consumes:
      - application/json
      parameters:
      - description: 企业资料上传
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CompanyAduitMaterialsReleaseReq'
      produces:
      - application/json
      responses:
        "200":
          description: 企业资料上传成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 企业资料上传
      tags:
      - CompanyAduitMaterialsRelease
  /certificate/get_audit_status:
    post:
      consumes:
      - application/json
      parameters:
      - description: 'user_id 用户id(update_type为1时必填), company_id 商户id(update_type为2时必填),
          update_type 更新类型(1.更新用户 2.更新商户) '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetAuditStatusReq'
      produces:
      - application/json
      responses:
        "200":
          description: 审核状态 0未审核 1审核中 2已审核
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/request.GetAuditStatusRes'
                msg:
                  type: string
              type: object
      summary: 获取审核状态
      tags:
      - GetAuditStatus
  /certificate/good_release:
    post:
      consumes:
      - application/json
      parameters:
      - description: 拍品发布
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ReleaseGoodReq'
      produces:
      - application/json
      responses:
        "200":
          description: 拍品发布成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 拍品发布
      tags:
      - ReleaseGoods
  /certificate/user_audit_material_release:
    post:
      consumes:
      - application/json
      parameters:
      - description: 个人资料上传
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserAduitMaterialsReleaseReq'
      produces:
      - application/json
      responses:
        "200":
          description: 个人资料上传成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 个人资料上传
      tags:
      - UserAduitMaterialsRelease
  /fileUploadAndDownload/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 上传文件示例
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 上传文件示例,返回包括文件详情
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 上传文件示例
      tags:
      - ExaFileUploadAndDownload
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
